###
GET   http://localhost:3500/api/cards/62fadc35605a8e6a2db7e35c


###
POST http://localhost:3500/api/cards
Content-Type: application/json

{
    "card_id":"4", 
    "type_card":"Amarelo", 
    "name":"Weedle", 
    "hp":"67",
    "attack":"56",
    "defense":"76", 
    "speed":"97",
    "energy":"82",
    "total_power":"378"
}