###
GET http://localhost:3500/cards/




###
POST http://localhost:3500/cards/
Content-Type: application/json

{
    "card_id":"6", 
    "type_card":"Amarelo", 
    "name":"Pikachu", 
    "hp":"69",
    "attack":"91",
    "defense":"55", 
    "speed":"96",
    "energy":"99",
    "total_power":"410"
}

###
PUT http://localhost:3500/api/cards/62fadcac605a8e6a2db7e35e
Content-Type: application/json

{
    "name": "Charmandel"
}

###
DELETE http://localhost:3500/api/cards/62fc08d05f357cf7661825ce

